### ISSUE TITLE
Cannot find server

### ISSUE THREAD

**Issue by Infinite-Blue-1042** [Resist-Tech/resist-tech.github.io#1]
There is not a server found because @aaravdave put an invalid end name, resist.ga . For now we have to keep it at resist.github.io, in order for it to align with the GitHub server.

**Comment by aaravdave** [comment]
I did now. Thanks, I tried but couldn't. Can you see it now?

**Comment by Infinite-Blue-1042** [comment]
No, I cannot see it, it is still named resist.ga
